# Generated by Django 2.2.14 on 2020-07-16 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalkLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, help_text='说说内容', null=True)),
                ('star', models.IntegerField(default=0)),
                ('reading', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(db_constraint=False, help_text='说说', on_delete=django.db.models.deletion.CASCADE, related_name='talk_log', to='chat.UserProfile')),
            ],
        ),
    ]
