# Generated by Django 2.2.14 on 2020-07-16 03:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_talklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='talklog',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='talklog',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
