# Generated by Django 2.2.14 on 2020-07-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200716_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, help_text='城市', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='qq_number',
            field=models.CharField(blank=True, help_text='qq号码', max_length=16, null=True),
        ),
    ]
