# Generated by Django 2.2.14 on 2020-07-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20200720_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_use_qq_img',
            field=models.BooleanField(default=False, help_text='是否使用QQ头像'),
        ),
    ]
