# Generated by Django 2.2.14 on 2020-07-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
