# Generated by Django 2.2.14 on 2020-08-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20200802_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='chat_type',
            field=models.CharField(choices=[('COMMON', '普通类型'), ('MUSIC', '音乐类型'), ('ROBOT', '机器人回复')], default='COMMON', help_text='房间类型', max_length=16),
        ),
    ]
